<?php

function islandora_custom_collection_grid($object) {
  $classes_to_add = array();
  $str_or_array = gettype($object['class']) == 'string' ? TRUE : FALSE ;
  if (!$str_or_array) {
  foreach ($object['class'] as $class){
      $classes_to_add[] = $class;
    }
  }
  else{
    $classes_to_add[] = $object['class'];
  }
    $classes_string =  stringify_classes_array($classes_to_add);
    $thumb_link = $object['thumb_link'];
    $title_link = filter_xss($object['title_link']);
    $output = array(
      'grid' => array(
        '#type' => 'markup',
        '#markup' =>
        "<dl class='islandora-basic-collection-object $classes_string>
          <dt class='islandora-basic-collection-thumb'> $thumb_link </dt>
          <dd class='islandora-basic-collection-caption'> $title_link </dd>
        </dl>",
    ),
  );
  return $output;
}

function islandora_basic_collection_display_element_info() {
  $types['grid_cell'] = array(
    '#type' => 'grid_cell',
    '#theme' => 'grid_cell',
  );
  return $types;
}

function stringify_classes_array($classes_array) {
  $string = implode(' ', $classes_array);
  return $string;
}

function theme_grid_cell($vars) {
  $cell = $vars['grid_cell'];
  $classes_string = $cell['classes'];
  $thumb_link = $cell['thumb'];
  $title_link = $cell['title'];
  $output = "<dl class='islandora-basic-collection-object $classes_string'><dt>$thumb_link</dt><dd>$title_link</dd></dl>";
  return $output;
}

function islandora_basic_collection_display_theme() {
  $theme['grid_cell'] = array(
      'render element' => 'grid_cell',
  );
  return $theme;
}

function islandora_basic_collection_display_preprocess_islandora_basic_collection_grid(&$variables) {
  foreach ($variables['collection_results'] as $result) {
    // add cmodels
    $pid = $result['object']['value'];
    $object = islandora_object_load($pid);
    $models = $object->models;
    $key = array_search('fedora-system:FedoraObject-3.0', $models);
    unset($models[$key]);
    $original_class = $variables['associated_objects_array'][$pid]['class'];
    $models[] = $original_class;
    $variables['associated_objects_array'][$pid]['class'] = $models;
  }
  //replace grid
  $grid_group = array();
  foreach ($variables['associated_objects_array'] as $object) {
    $thumb_link = $object['thumb_link'];
    $title_link = filter_xss($object['title_link']);
    foreach ($variables['associated_objects_array'] as $object) {
      $models = isset($object['models']);
      $grid_group[] = $models ? islandora_custom_collection_grid($object, $object['models']) : islandora_custom_collection_grid($object); ;
    }
    $variables['rendered_grids'] = $grid_group;
  }
}

function islandora_basic_collection_display_theme_registry_alter(&$theme_registry) {
  $path = drupal_get_path('module','islandora_basic_collection_display');
  $template_files = drupal_find_theme_templates($theme_registry, '.tpl.php', $path);
  foreach ($template_files as $key => $file) {
    $theme_registry[$key]['theme path']= $path;
    $theme_registry[$key] = array_merge($theme_registry[$key], $file);
  }
}
